language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install pep8"

env:
    MYAPP_SECRET_KEY=travis
    
before_script:
  - mysql -e 'create database blog;'    
  - "pep8 *"
# command to run tests
script: python manage.py test
